//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Cost : XPCustomObject
    {

        #region Properties
        public DateTime YearMonth 
        {
            get 
            {
                return new DateTime(Date.Year, Date.Month, 1); 
            }
        }
        public int Month
        {
            get
            {
                return Date.Month;
            }
        }
        #endregion

        #region XPO Fields
        Guid fcostID;
        [Key(true)]
        public Guid costID
        {
            get { return fcostID; }
            set { SetPropertyValue<Guid>("costID", ref fcostID, value); }
        }

        int ftas_TNR_ENTRY;
        public int tas_TNR_ENTRY
        {
            get { return ftas_TNR_ENTRY; }
            set { SetPropertyValue<int>("tas_TNR_ENTRY", ref ftas_TNR_ENTRY, value); }
        }

        Supplier ftas_TNR_SUPPLIER;
        [Size(35)]
        public Supplier tas_TNR_SUPPLIER
        {
            get { return ftas_TNR_SUPPLIER; }
            set { SetPropertyValue<Supplier>("tas_TNR_SUPPLIER", ref ftas_TNR_SUPPLIER, value); }
        }

        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }

        decimal fPurchaseAmount;
        public decimal PurchaseAmount
        {
            get { return fPurchaseAmount; }
            set { SetPropertyValue<decimal>("PurchaseAmount", ref fPurchaseAmount, value); }
        }
        #endregion
        
        #region FieldsClass
        private static FieldsClass _Fields;
        public new static FieldsClass Fields
        {
            get
            {
                if (ReferenceEquals(_Fields, null))
                    _Fields = new FieldsClass();
                return _Fields;
            }
        }
        //Created/Updated: MATCOM\dries on DEV1 at 28/01/2013 1:09
        public new class FieldsClass : XPCustomObject.FieldsClass
        {
            public FieldsClass()
                : base()
            {
            }
            public FieldsClass(string propertyName)
                : base(propertyName)
            {
            }
            public OperandProperty costID
            {
                get
                {
                    return new OperandProperty(GetNestedName("costID"));
                }
            }
            public OperandProperty tas_TNR_ENTRY
            {
                get
                {
                    return new OperandProperty(GetNestedName("tas_TNR_ENTRY"));
                }
            }
            public TIS.Model.Internal.Supplier.FieldsClass tas_TNR_SUPPLIER
            {
                get
                {
                    return new TIS.Model.Internal.Supplier.FieldsClass(GetNestedName("tas_TNR_SUPPLIER"));
                }
            }
            public OperandProperty Date
            {
                get
                {
                    return new OperandProperty(GetNestedName("Date"));
                }
            }
            public OperandProperty PurchaseAmount
            {
                get
                {
                    return new OperandProperty(GetNestedName("PurchaseAmount"));
                }
            }
        }
        #endregion
        
    }

}
