//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Employee : XPCustomObject
    {
        Guid fempID;
        [Key(true)]
        public Guid empID
        {
            get { return fempID; }
            set { SetPropertyValue<Guid>("empID", ref fempID, value); }
        }
        int ftranscID;
        public int transcID
        {
            get { return ftranscID; }
            set { SetPropertyValue<int>("transcID", ref ftranscID, value); }
        }
        int ftransiID;
        public int transiID
        {
            get { return ftransiID; }
            set { SetPropertyValue<int>("transiID", ref ftransiID, value); }
        }
        int ftranscLanguage;
        public int transcLanguage
        {
            get { return ftranscLanguage; }
            set { SetPropertyValue<int>("transcLanguage", ref ftranscLanguage, value); }
        }
        Guid flanID;
        public Guid lanID
        {
            get { return flanID; }
            set { SetPropertyValue<Guid>("lanID", ref flanID, value); }
        }
        string fEmail;
        [Size(382)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fName;
        [Size(382)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fSurname;
        [Size(382)]
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>("Surname", ref fSurname, value); }
        }
        bool fArchive;
        public bool Archive
        {
            get { return fArchive; }
            set { SetPropertyValue<bool>("Archive", ref fArchive, value); }
        }
        bool fRepeatMail;
        public bool RepeatMail
        {
            get { return fRepeatMail; }
            set { SetPropertyValue<bool>("RepeatMail", ref fRepeatMail, value); }
        }
    }

}
