//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Fuel : XPCustomObject
    {
        Guid ffuelID;
        [Key(true)]
        public Guid fuelID
        {
            get { return ffuelID; }
            set { SetPropertyValue<Guid>("fuelID", ref ffuelID, value); }
        }
        int ftransi_TNR_reg;
        public int transi_TNR_reg
        {
            get { return ftransi_TNR_reg; }
            set { SetPropertyValue<int>("transi_TNR_reg", ref ftransi_TNR_reg, value); }
        }
        int ftransi_TNR_person;
        public int transi_TNR_person
        {
            get { return ftransi_TNR_person; }
            set { SetPropertyValue<int>("transi_TNR_person", ref ftransi_TNR_person, value); }
        }
        int ftransi_TNR_mat;
        public int transi_TNR_mat
        {
            get { return ftransi_TNR_mat; }
            set { SetPropertyValue<int>("transi_TNR_mat", ref ftransi_TNR_mat, value); }
        }
        int ftransi_TNR_pump;
        public int transi_TNR_pump
        {
            get { return ftransi_TNR_pump; }
            set { SetPropertyValue<int>("transi_TNR_pump", ref ftransi_TNR_pump, value); }
        }
        int ftransi_TNR_tank;
        public int transi_TNR_tank
        {
            get { return ftransi_TNR_tank; }
            set { SetPropertyValue<int>("transi_TNR_tank", ref ftransi_TNR_tank, value); }
        }
        int ftransi_FuelType;
        public int transi_FuelType
        {
            get { return ftransi_FuelType; }
            set { SetPropertyValue<int>("transi_FuelType", ref ftransi_FuelType, value); }
        }
        int ftransc_FuelId;
        public int transc_FuelId
        {
            get { return ftransc_FuelId; }
            set { SetPropertyValue<int>("transc_FuelId", ref ftransc_FuelId, value); }
        }
        int ftransc_NawID;
        public int transc_NawID
        {
            get { return ftransc_NawID; }
            set { SetPropertyValue<int>("transc_NawID", ref ftransc_NawID, value); }
        }
        double ftransc_Date;
        public double transc_Date
        {
            get { return ftransc_Date; }
            set { SetPropertyValue<double>("transc_Date", ref ftransc_Date, value); }
        }
        int ftransc_PriveBedrijf;
        public int transc_PriveBedrijf
        {
            get { return ftransc_PriveBedrijf; }
            set { SetPropertyValue<int>("transc_PriveBedrijf", ref ftransc_PriveBedrijf, value); }
        }
        string ftransc_Product;
        [Size(382)]
        public string transc_Product
        {
            get { return ftransc_Product; }
            set { SetPropertyValue<string>("transc_Product", ref ftransc_Product, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        string fEmployeeName;
        [Size(25)]
        public string EmployeeName
        {
            get { return fEmployeeName; }
            set { SetPropertyValue<string>("EmployeeName", ref fEmployeeName, value); }
        }
        string fEmployee;
        [Size(766)]
        public string Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<string>("Employee", ref fEmployee, value); }
        }
        string fVehicleLicensePlate;
        [Size(382)]
        public string VehicleLicensePlate
        {
            get { return fVehicleLicensePlate; }
            set { SetPropertyValue<string>("VehicleLicensePlate", ref fVehicleLicensePlate, value); }
        }
        int fVehicleKilometreCounter;
        public int VehicleKilometreCounter
        {
            get { return fVehicleKilometreCounter; }
            set { SetPropertyValue<int>("VehicleKilometreCounter", ref fVehicleKilometreCounter, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>("Quantity", ref fQuantity, value); }
        }
        decimal fFulltank;
        public decimal Fulltank
        {
            get { return fFulltank; }
            set { SetPropertyValue<decimal>("Fulltank", ref fFulltank, value); }
        }
        decimal fUnityPrice;
        public decimal UnityPrice
        {
            get { return fUnityPrice; }
            set { SetPropertyValue<decimal>("UnityPrice", ref fUnityPrice, value); }
        }
        decimal fTotalPrice;
        public decimal TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<decimal>("TotalPrice", ref fTotalPrice, value); }
        }
        int fUnit;
        public int Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<int>("Unit", ref fUnit, value); }
        }
        string fSupplier;
        [Size(382)]
        public string Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<string>("Supplier", ref fSupplier, value); }
        }
        string fLocation;
        [Size(382)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>("Location", ref fLocation, value); }
        }
        int fFueltype;
        public int Fueltype
        {
            get { return fFueltype; }
            set { SetPropertyValue<int>("Fueltype", ref fFueltype, value); }
        }
        decimal fBTW;
        public decimal BTW
        {
            get { return fBTW; }
            set { SetPropertyValue<decimal>("BTW", ref fBTW, value); }
        }
        bool fPrivateTanking;
        public bool PrivateTanking
        {
            get { return fPrivateTanking; }
            set { SetPropertyValue<bool>("PrivateTanking", ref fPrivateTanking, value); }
        }
        bool fCompanyTanking;
        public bool CompanyTanking
        {
            get { return fCompanyTanking; }
            set { SetPropertyValue<bool>("CompanyTanking", ref fCompanyTanking, value); }
        }
        bool fInvoiceReceived;
        public bool InvoiceReceived
        {
            get { return fInvoiceReceived; }
            set { SetPropertyValue<bool>("InvoiceReceived", ref fInvoiceReceived, value); }
        }
        bool fInvoiceOK;
        public bool InvoiceOK
        {
            get { return fInvoiceOK; }
            set { SetPropertyValue<bool>("InvoiceOK", ref fInvoiceOK, value); }
        }
        decimal fQuantityCorrection;
        public decimal QuantityCorrection
        {
            get { return fQuantityCorrection; }
            set { SetPropertyValue<decimal>("QuantityCorrection", ref fQuantityCorrection, value); }
        }
        string fDateMailForbiddenFueling;
        [Size(14)]
        public string DateMailForbiddenFueling
        {
            get { return fDateMailForbiddenFueling; }
            set { SetPropertyValue<string>("DateMailForbiddenFueling", ref fDateMailForbiddenFueling, value); }
        }
    }

}
