//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class MaterialType : XPCustomObject
    {
        Guid fmattypID;
        [Key(true)]
        public Guid mattypID
        {
            get { return fmattypID; }
            set { SetPropertyValue<Guid>("mattypID", ref fmattypID, value); }
        }
        Guid fmatcatID;
        public Guid matcatID
        {
            get { return fmatcatID; }
            set { SetPropertyValue<Guid>("matcatID", ref fmatcatID, value); }
        }
        string fType;
        [Size(50)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>("Type", ref fType, value); }
        }
    }

}
