//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class MaterialCategory : XPCustomObject
    {
        Guid fmatcatID;
        [Key(true)]
        public Guid matcatID
        {
            get { return fmatcatID; }
            set { SetPropertyValue<Guid>("matcatID", ref fmatcatID, value); }
        }
        string fCategory;
        [Size(50)]
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>("Category", ref fCategory, value); }
        }
    }

}
