//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class MaterialRevision : XPCustomObject
    {
        Guid fmatrevID;
        [Key(true)]
        public Guid matrevID
        {
            get { return fmatrevID; }
            set { SetPropertyValue<Guid>("matrevID", ref fmatrevID, value); }
        }
        Guid fmaintID;
        public Guid maintID
        {
            get { return fmaintID; }
            set { SetPropertyValue<Guid>("maintID", ref fmaintID, value); }
        }
        string fRevision;
        [Size(SizeAttribute.Unlimited)]
        public string Revision
        {
            get { return fRevision; }
            set { SetPropertyValue<string>("Revision", ref fRevision, value); }
        }
        string fAnswer;
        [Size(SizeAttribute.Unlimited)]
        public string Answer
        {
            get { return fAnswer; }
            set { SetPropertyValue<string>("Answer", ref fAnswer, value); }
        }
        string fCategory;
        [Size(255)]
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>("Category", ref fCategory, value); }
        }
    }

}
