//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Material : XPCustomObject
    {
        Guid fmatID;
        [Key(true)]
        public Guid matID
        {
            get { return fmatID; }
            set { SetPropertyValue<Guid>("matID", ref fmatID, value); }
        }
        Guid fmatcatID;
        public Guid matcatID
        {
            get { return fmatcatID; }
            set { SetPropertyValue<Guid>("matcatID", ref fmatcatID, value); }
        }
        Guid fmattypID;
        public Guid mattypID
        {
            get { return fmattypID; }
            set { SetPropertyValue<Guid>("mattypID", ref fmattypID, value); }
        }
        Guid fmatstypID;
        public Guid matstypID
        {
            get { return fmatstypID; }
            set { SetPropertyValue<Guid>("matstypID", ref fmatstypID, value); }
        }
        Guid fempIDCreator;
        public Guid empIDCreator
        {
            get { return fempIDCreator; }
            set { SetPropertyValue<Guid>("empIDCreator", ref fempIDCreator, value); }
        }
        Guid fempIDResponsable;
        public Guid empIDResponsable
        {
            get { return fempIDResponsable; }
            set { SetPropertyValue<Guid>("empIDResponsable", ref fempIDResponsable, value); }
        }
        Guid fvehID;
        public Guid vehID
        {
            get { return fvehID; }
            set { SetPropertyValue<Guid>("vehID", ref fvehID, value); }
        }
        Guid fsupID;
        public Guid supID
        {
            get { return fsupID; }
            set { SetPropertyValue<Guid>("supID", ref fsupID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>("Type", ref fType, value); }
        }
        string fSerieNumber;
        [Size(50)]
        public string SerieNumber
        {
            get { return fSerieNumber; }
            set { SetPropertyValue<string>("SerieNumber", ref fSerieNumber, value); }
        }
        string fInternalNumber;
        [Size(50)]
        public string InternalNumber
        {
            get { return fInternalNumber; }
            set { SetPropertyValue<string>("InternalNumber", ref fInternalNumber, value); }
        }
        string fPurchasedOn;
        [Size(8)]
        public string PurchasedOn
        {
            get { return fPurchasedOn; }
            set { SetPropertyValue<string>("PurchasedOn", ref fPurchasedOn, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>("Price", ref fPrice, value); }
        }
        string fNextMaintenance;
        [Size(8)]
        public string NextMaintenance
        {
            get { return fNextMaintenance; }
            set { SetPropertyValue<string>("NextMaintenance", ref fNextMaintenance, value); }
        }
        int fMaintenanceFrequency;
        public int MaintenanceFrequency
        {
            get { return fMaintenanceFrequency; }
            set { SetPropertyValue<int>("MaintenanceFrequency", ref fMaintenanceFrequency, value); }
        }
        bool fBroken;
        public bool Broken
        {
            get { return fBroken; }
            set { SetPropertyValue<bool>("Broken", ref fBroken, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
    }

}
