//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class MaterialSubType : XPCustomObject
    {
        Guid fmatstypID;
        [Key(true)]
        public Guid matstypID
        {
            get { return fmatstypID; }
            set { SetPropertyValue<Guid>("matstypID", ref fmatstypID, value); }
        }
        Guid fmattypID;
        public Guid mattypID
        {
            get { return fmattypID; }
            set { SetPropertyValue<Guid>("mattypID", ref fmattypID, value); }
        }
        string fSubType;
        [Size(50)]
        public string SubType
        {
            get { return fSubType; }
            set { SetPropertyValue<string>("SubType", ref fSubType, value); }
        }
    }

}
