//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Memo : XPCustomObject
    {
        Guid fmemoID;
        [Key(true)]
        public Guid memoID
        {
            get { return fmemoID; }
            set { SetPropertyValue<Guid>("memoID", ref fmemoID, value); }
        }
        Guid fmatID;
        public Guid matID
        {
            get { return fmatID; }
            set { SetPropertyValue<Guid>("matID", ref fmatID, value); }
        }
        string fDateTime;
        [Size(14)]
        public string DateTime
        {
            get { return fDateTime; }
            set { SetPropertyValue<string>("DateTime", ref fDateTime, value); }
        }
        string fMemo1;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"Memo")]
        public string Memo1
        {
            get { return fMemo1; }
            set { SetPropertyValue<string>("Memo1", ref fMemo1, value); }
        }
    }

}
