//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class ParameterSystem : XPCustomObject
    {
        Guid fparID;
        [Key(true)]
        public Guid parID
        {
            get { return fparID; }
            set { SetPropertyValue<Guid>("parID", ref fparID, value); }
        }
        string fKeyName;
        public string KeyName
        {
            get { return fKeyName; }
            set { SetPropertyValue<string>("KeyName", ref fKeyName, value); }
        }
        string fValue1;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"Value")]
        public string Value1
        {
            get { return fValue1; }
            set { SetPropertyValue<string>("Value1", ref fValue1, value); }
        }
    }

}
