//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Popup : XPCustomObject
    {
        Guid fpopupID;
        [Key(true)]
        public Guid popupID
        {
            get { return fpopupID; }
            set { SetPropertyValue<Guid>("popupID", ref fpopupID, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        int fRepeat;
        public int Repeat
        {
            get { return fRepeat; }
            set { SetPropertyValue<int>("Repeat", ref fRepeat, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        string fCreationDate;
        [Size(8)]
        public string CreationDate
        {
            get { return fCreationDate; }
            set { SetPropertyValue<string>("CreationDate", ref fCreationDate, value); }
        }
        string fTime;
        [Size(6)]
        public string Time
        {
            get { return fTime; }
            set { SetPropertyValue<string>("Time", ref fTime, value); }
        }
        bool fShowDirect;
        public bool ShowDirect
        {
            get { return fShowDirect; }
            set { SetPropertyValue<bool>("ShowDirect", ref fShowDirect, value); }
        }
    }

}
