//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Revision : XPCustomObject
    {
        Guid frevID;
        [Key(true)]
        public Guid revID
        {
            get { return frevID; }
            set { SetPropertyValue<Guid>("revID", ref frevID, value); }
        }
        Guid fmatcatID;
        public Guid matcatID
        {
            get { return fmatcatID; }
            set { SetPropertyValue<Guid>("matcatID", ref fmatcatID, value); }
        }
        Guid fmattypID;
        public Guid mattypID
        {
            get { return fmattypID; }
            set { SetPropertyValue<Guid>("mattypID", ref fmattypID, value); }
        }
        Guid fmatstypID;
        public Guid matstypID
        {
            get { return fmatstypID; }
            set { SetPropertyValue<Guid>("matstypID", ref fmatstypID, value); }
        }
        string fRevision1;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"Revision")]
        public string Revision1
        {
            get { return fRevision1; }
            set { SetPropertyValue<string>("Revision1", ref fRevision1, value); }
        }
    }

}
