//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Supplier : XPCustomObject
    {
        Guid fsupID;
        [Key(true)]
        public Guid supID
        {
            get { return fsupID; }
            set { SetPropertyValue<Guid>("supID", ref fsupID, value); }
        }
        int ftranscID;
        public int transcID
        {
            get { return ftranscID; }
            set { SetPropertyValue<int>("transcID", ref ftranscID, value); }
        }
        int ftasID;
        public int tasID
        {
            get { return ftasID; }
            set { SetPropertyValue<int>("tasID", ref ftasID, value); }
        }
        string fName;
        [Size(35)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fName2;
        [Size(35)]
        public string Name2
        {
            get { return fName2; }
            set { SetPropertyValue<string>("Name2", ref fName2, value); }
        }
        string fStreet;
        [Size(60)]
        public string Street
        {
            get { return fStreet; }
            set { SetPropertyValue<string>("Street", ref fStreet, value); }
        }
        string fHouseNumber;
        [Size(10)]
        public string HouseNumber
        {
            get { return fHouseNumber; }
            set { SetPropertyValue<string>("HouseNumber", ref fHouseNumber, value); }
        }
        string fZipcode;
        [Size(10)]
        public string Zipcode
        {
            get { return fZipcode; }
            set { SetPropertyValue<string>("Zipcode", ref fZipcode, value); }
        }
        string fTown;
        [Size(35)]
        public string Town
        {
            get { return fTown; }
            set { SetPropertyValue<string>("Town", ref fTown, value); }
        }
        string fCountry;
        [Size(10)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>("Country", ref fCountry, value); }
        }
        string fVAT;
        [Size(20)]
        public string VAT
        {
            get { return fVAT; }
            set { SetPropertyValue<string>("VAT", ref fVAT, value); }
        }
        string fPhone;
        [Size(60)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fLanguage;
        [Size(10)]
        public string Language
        {
            get { return fLanguage; }
            set { SetPropertyValue<string>("Language", ref fLanguage, value); }
        }
        string fCurrency;
        [Size(10)]
        public string Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<string>("Currency", ref fCurrency, value); }
        }
        string fEmail;
        [Size(60)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        [Association(@"BoardComputer.tasID_Supplier")]
        public XPCollection<BoardComputer> BoardComputers
        {
            get { return GetCollection<BoardComputer>(@"BoardComputers"); }
        }   
       
    }

}
