//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class TaskSchedule : XPCustomObject
    {
        Guid ftschedID;
        [Key(true)]
        public Guid tschedID
        {
            get { return ftschedID; }
            set { SetPropertyValue<Guid>("tschedID", ref ftschedID, value); }
        }
        Guid ftaskID;
        public Guid taskID
        {
            get { return ftaskID; }
            set { SetPropertyValue<Guid>("taskID", ref ftaskID, value); }
        }
        Guid fschedID;
        public Guid schedID
        {
            get { return fschedID; }
            set { SetPropertyValue<Guid>("schedID", ref fschedID, value); }
        }
    }

}
