//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class TaskPeople : XPCustomObject
    {
        Guid ftpeopID;
        [Key(true)]
        public Guid tpeopID
        {
            get { return ftpeopID; }
            set { SetPropertyValue<Guid>("tpeopID", ref ftpeopID, value); }
        }
        Guid ftaskID;
        public Guid taskID
        {
            get { return ftaskID; }
            set { SetPropertyValue<Guid>("taskID", ref ftaskID, value); }
        }
        Guid fempID;
        public Guid empID
        {
            get { return fempID; }
            set { SetPropertyValue<Guid>("empID", ref fempID, value); }
        }
        Guid fsupID;
        public Guid supID
        {
            get { return fsupID; }
            set { SetPropertyValue<Guid>("supID", ref fsupID, value); }
        }
        Guid fcusID;
        public Guid cusID
        {
            get { return fcusID; }
            set { SetPropertyValue<Guid>("cusID", ref fcusID, value); }
        }
        Guid funkID;
        public Guid unkID
        {
            get { return funkID; }
            set { SetPropertyValue<Guid>("unkID", ref funkID, value); }
        }
        bool fAssignee;
        public bool Assignee
        {
            get { return fAssignee; }
            set { SetPropertyValue<bool>("Assignee", ref fAssignee, value); }
        }
        bool fReporter;
        public bool Reporter
        {
            get { return fReporter; }
            set { SetPropertyValue<bool>("Reporter", ref fReporter, value); }
        }
    }

}
