//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    [NonPersistent]
    public partial class TurnOverCustomerAscendingResult
    {
        public string Name { get; set; }
        public decimal MonthAverageYear { get; set; }
        public decimal MonthAverageLastYear { get; set; }
        public decimal Difference { get; set; }
    }

}
