//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Unknown : XPCustomObject
    {
        Guid funkID;
        [Key(true)]
        public Guid unkID
        {
            get { return funkID; }
            set { SetPropertyValue<Guid>("unkID", ref funkID, value); }
        }
        string fEmail;
        [Size(382)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
    }

}
