//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Users : XPCustomObject
    {
        Guid fusrID;
        [Key(true)]
        public Guid usrID
        {
            get { return fusrID; }
            set { SetPropertyValue<Guid>("usrID", ref fusrID, value); }
        }
        Guid fempID;
        public Guid empID
        {
            get { return fempID; }
            set { SetPropertyValue<Guid>("empID", ref fempID, value); }
        }
        string fSurname;
        [Size(200)]
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>("Surname", ref fSurname, value); }
        }
        string fName;
        [Size(200)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fLogin;
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>("Login", ref fLogin, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        byte[] fSecurity;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Security
        {
            get { return fSecurity; }
            set { SetPropertyValue<byte[]>("Security", ref fSecurity, value); }
        }
        bool fHasPopups;
        public bool HasPopups
        {
            get { return fHasPopups; }
            set { SetPropertyValue<bool>("HasPopups", ref fHasPopups, value); }
        }
    }

}
