//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class VehicleMileage : XPCustomObject
    {
        Guid fvehmID;
        [Key(true)]
        public Guid vehmID
        {
            get { return fvehmID; }
            set { SetPropertyValue<Guid>("vehmID", ref fvehmID, value); }
        }
        int ftransi_TNR_mat;
        public int transi_TNR_mat
        {
            get { return ftransi_TNR_mat; }
            set { SetPropertyValue<int>("transi_TNR_mat", ref ftransi_TNR_mat, value); }
        }
        string ftransi_NM_mat;
        [Size(50)]
        public string transi_NM_mat
        {
            get { return ftransi_NM_mat; }
            set { SetPropertyValue<string>("transi_NM_mat", ref ftransi_NM_mat, value); }
        }
        string fDate;
        [Size(8)]
        public string Date
        {
            get { return fDate; }
            set { SetPropertyValue<string>("Date", ref fDate, value); }
        }
        int fMileage;
        public int Mileage
        {
            get { return fMileage; }
            set { SetPropertyValue<int>("Mileage", ref fMileage, value); }
        }
    }

}
