//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class VehicleType : XPCustomObject
    {
        int fvehtID;
        [Key(true)]
        public int vehtID
        {
            get { return fvehtID; }
            set { SetPropertyValue<int>("vehtID", ref fvehtID, value); }
        }
        int ftransc_VehicleType;
        public int transc_VehicleType
        {
            get { return ftransc_VehicleType; }
            set { SetPropertyValue<int>("transc_VehicleType", ref ftransc_VehicleType, value); }
        }
        string fType;
        [Size(50)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>("Type", ref fType, value); }
        }
    }

}
