//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TIS.Model.Internal
{

    public partial class Vehicle : XPCustomObject
    {
        Guid fvehID;
         [Key(true)]
        public Guid vehID
        {
            get { return fvehID; }
            set { SetPropertyValue<Guid>("vehID", ref fvehID, value); }
        }
        int ftransc_VehicleID;
        public int transc_VehicleID
        {
            get { return ftransc_VehicleID; }
            set { SetPropertyValue<int>("transc_VehicleID", ref ftransc_VehicleID, value); }
        }
        int ftransc_VehicleType;
        public int transc_VehicleType
        {
            get { return ftransc_VehicleType; }
            set { SetPropertyValue<int>("transc_VehicleType", ref ftransc_VehicleType, value); }
        }
        string fName;
        [Size(382)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fLicenseNumber;
        [Size(382)]
        public string LicenseNumber
        {
            get { return fLicenseNumber; }
            set { SetPropertyValue<string>("LicenseNumber", ref fLicenseNumber, value); }
        }
        int fEuronorm;
        public int Euronorm
        {
            get { return fEuronorm; }
            set { SetPropertyValue<int>("Euronorm", ref fEuronorm, value); }
        }
        string fChassis;
        [Size(382)]
        public string Chassis
        {
            get { return fChassis; }
            set { SetPropertyValue<string>("Chassis", ref fChassis, value); }
        }
        string fBrand;
        [Size(382)]
        public string Brand
        {
            get { return fBrand; }
            set { SetPropertyValue<string>("Brand", ref fBrand, value); }
        }
        string fIcon;
        [Size(382)]
        public string Icon
        {
            get { return fIcon; }
            set { SetPropertyValue<string>("Icon", ref fIcon, value); }
        }
        string fVehicleType;
        [Size(50)]
        public string VehicleType
        {
            get { return fVehicleType; }
            set { SetPropertyValue<string>("VehicleType", ref fVehicleType, value); }
        }
        bool fContactTransics;
        public bool ContactTransics
        {
            get { return fContactTransics; }
            set { SetPropertyValue<bool>("ContactTransics", ref fContactTransics, value); }
        }
        [Association(@"BoardComputer.vehID_Vehicle")]
        public XPCollection<BoardComputer> BoardComputers
        {
            get { return GetCollection<BoardComputer>(@"BoardComputers"); }
        }   
    }

}
